org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Mod Properties
  group=com.presencefootsteps
  displayname=Presence Footsteps (NeoForge)
  mod_authors=Hurricaaane (Ha3), Sollace, Paint_Ninja, ZCRAFT
  mod_description=An overly complicated sound mod
  url=http://presencefootsteps.ha3.eu

# NeoForge
mod_name=Presence Footsteps (NeoForge)
mod_license=PolyForm Shield License 1.0.0
mod_id=presencefootsteps
mod_version=1.21.11-1.12.4-beta.2
minecraft_version=1.21.11
minecraft_version_range=[1.21.11,1.21.12)
neo_version=21.11.44
neo_version_range=[21.11,21.12)
loader_version_range=[1,)
